name: Build Matlab Standalone
on:
  push:
    tags:
      - "v*.*.*"

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_BATCH_TOKEN }}
jobs:
  build_matlab_standalone:
    name: Build Matlab Standalone
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: MATLAB_Compiler
          cache: true
      - name: Checkout SPM
        uses: actions/checkout@v4
        with:
          repository: spm/spm

      # 1) Add SPM with subfolders to the path 2) Run spm_make_standalone in matlab
      - name: Build Matlab Standalone
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath(genpath('.'));
            savepath;
            spm_make_standalone

      # Compress to tar.gz or zip
      - name: Compress Unix
        if: ${{ runner.os != 'Windows' }}
        run: |
          echo "ZIP_ENDING=tar.gz" >> $GITHUB_ENV
          echo "ZIP_TYPE=gzip" >> $GITHUB_ENV
          mv ../standalone standalone_${{ matrix.os }}_${{ github.event.release.tag_name }}
          tar -vczf standalone_${{ matrix.os }}_${{ github.event.release.tag_name }}.tar.gz standalone_${{ matrix.os }}_${{ github.event.release.tag_name }}
      - name: Compress Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo "ZIP_ENDING=zip" >> $env:GITHUB_ENV
          echo "ZIP_TYPE=zip" >> $env:GITHUB_ENV
          Compress-Archive -Path '../standalone/*' -DestinationPath 'standalone_${{ matrix.os }}_${{ github.event.release.tag_name }}.zip
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: standalone*.${{ env.ZIP_ENDING }}
          
