name: Build Matlab Standalone
on:
  push:
    tags:
      - "v*.*.*"

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_BATCH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  build_matlab_standalone:
    name: Build Matlab Standalone
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ["R2021a", "R2021b", "R2022a", "R2022b", "R2023a", "R2023b", "R2024a", "R2024b"]
        os: ["ubuntu-latest", "macos-13", "macos-latest", "windows-latest"] # macos-13 has Intel architecture, macos-latest has Apple Silicon
        exclude:
          - os: windows-latest
            version: "R2021a" # Compiler not available
          - os: windows-latest
            version: "R2021b" # Compiler not available
          - os: macos-latest
            version: "R2021a" # Apple Silicon version not available
          - os: macos-latest
            version: "R2021b" # Apple Silicon version not available
          - os: macos-latest
            version: "R2022a" # Apple Silicon version not available
          - os: macos-latest
            version: "R2022b" # Apple Silicon version not available
          - os: macos-latest
            version: "R2023a" # Apple Silicon version not available

    steps:
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: MATLAB_Compiler
      - name: Checkout SPM
        uses: actions/checkout@v4
        with:
          repository: spm/spm

      # 1) Add SPM with subfolders to the path 2) Run spm_make_standalone in matlab
      - name: Build Matlab Standalone
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath(genpath('.'));
            savepath;
            spm_make_standalone

      # Define OS names
      - name: Define OS Names
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            echo "OS_NAME=macOS_ARM" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "macos-13" ]; then
            echo "OS_NAME=macOS_Intel" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            echo "OS_NAME=Windows" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            echo "OS_NAME=Linux" >> $GITHUB_ENV
          else
            echo "OS_NAME=Unknown OS" >> $GITHUB_ENV
          fi

      # Compress to tar.gz or zip
      - name: Compress Unix
        if: ${{ runner.os != 'Windows' }}
        run: |
          echo "ZIP_ENDING=tar.gz" >> $GITHUB_ENV
          echo "ZIP_TYPE=gzip" >> $GITHUB_ENV
          mv ../standalone spm__${{ github.event.release.tag_name }}_${{ env.OS_NAME }}_${{ matrix.version }}
          tar -vczf spm__${{ github.event.release.tag_name }}_${{ env.OS_NAME }}_${{ matrix.version }}.tar.gz spm__${{ github.event.release.tag_name }}_${{ env.OS_NAME }}_${{ matrix.version }}
      - name: Compress Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo "ZIP_ENDING=zip" >> $env:GITHUB_ENV
          echo "ZIP_TYPE=zip" >> $env:GITHUB_ENV
          Compress-Archive -Path '../standalone/*' -DestinationPath 'spm__${{ github.event.release.tag_name }}_${{ env.OS_NAME }}_${{ matrix.version }}.zip
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: standalone*.${{ env.ZIP_ENDING }}
          
