name: Build Matlab Standalone
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_BATCH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  build_matlab_standalone:
    name: Build Matlab Standalone
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ["latest"] #["R2021a", "R2021b", "R2022a", "R2022b", "R2023a", "R2023b", "R2024a", "R2024b"]
        os: ["ubuntu-latest", "macos-13", "macos-latest", "windows-latest"] # macos-13 has Intel architecture, macos-latest has Apple Silicon
        include:
          - os: ubuntu-latest
            os_name: Linux
          - os: macos-13
            os_name: macOS_Intel
          - os: macos-latest
            os_name: macOS_Apple_Silicon
          - os: windows-latest
            os_name: Windows
        exclude:
          - os: windows-latest
            version: "R2021a" # Compiler not available
          - os: windows-latest
            version: "R2021b" # Compiler not available
          - os: macos-latest
            version: "R2021a" # Apple Silicon version not available
          - os: macos-latest
            version: "R2021b" # Apple Silicon version not available
          - os: macos-latest
            version: "R2022a" # Apple Silicon version not available
          - os: macos-latest
            version: "R2022b" # Apple Silicon version not available
          - os: macos-latest
            version: "R2023a" # Apple Silicon version not available

    steps:
      - name: Set up MATLAB
        id: setup_matlab
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{matrix.version}}
          products: MATLAB_Compiler

      - name: Extract MATLAB Version for Linux/Mac
        if: runner.os != 'Windows'
        run: |
          # Get MATLAB installation path (e.g., /opt/hostedtoolcache/MATLAB/2024.2.999/x64/bin/matlab)
          matlab_path=$(which matlab)
          # Go up two levels to get the folder containing the version (e.g., /opt/hostedtoolcache/MATLAB/2024.2.999)
          matlab_install_dir=$(dirname "$(dirname "$(dirname "$matlab_path")")")
          # Extract the base directory name (e.g., "2024.2.999") and use the first part as the version (R2024b)
          matlab_base_version=$(basename "$matlab_install_dir" | cut -d. -f1,2)
          # Split the major and minor versions
          IFS='.' read -r major minor <<< "$matlab_base_version"
          if [[ "$minor" == "1" ]]; then
              matlab_version="R${major}a"
          elif [[ "$minor" == "2" ]]; then
              matlab_version="R${major}b"
          fi

          echo "Extracted MATLAB Version: $matlab_version"
          echo "MATLAB_VERSION=$matlab_version" >> $GITHUB_ENV

      - name: Extract MATLAB Version for Windows
        if: runner.os == 'Windows'
        run: |
          # Get MATLAB installation path (e.g., C:\hostedtoolcache\windows\MATLAB\R2024b\bin\matlab.exe)
          $matlab_path = (Get-Command matlab).Source
          # Go up two levels to get the folder containing the version (e.g., C:\hostedtoolcache\windows\MATLAB\R2024b)
          $matlab_install_dir = echo "$matlab_path" | ForEach-Object { Split-Path -Parent $_ } | ForEach-Object { Split-Path -Parent $_ }
          # Extract the base directory name (e.g., "R2024b")
          $matlab_version = Split-Path "$matlab_install_dir" -Leaf
          echo "Extracted MATLAB Version: $matlab_version"
          echo "MATLAB_VERSION=$matlab_version" >> $GITHUB_ENV

      - name: Checkout SPM
        uses: actions/checkout@v4
        with:
          repository: spm/spm

      # 1) Add SPM with subfolders to the path 2) Run spm_make_standalone in matlab
      - name: Build Matlab Standalone
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath(genpath('.'));
            savepath;
            spm_make_standalone
            
      # Compress to tar.gz or zip
      - name: Compress Unix
        if: ${{ runner.os != 'Windows' }}
        run: |
          mv ../standalone spm_${{ github.ref_name }}_${{ matrix.os_name }}_${{ env.MATLAB_VERSION }}
          zip -r spm_${{ github.ref_name }}_${{ env.MATLAB_VERSION }}_${{ matrix.version }}.zip spm_${{ github.ref_name }}_${{ matrix.os_name }}_${{ matrix.version }}

      - name: Compress Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          Compress-Archive -Path '../standalone/*' -DestinationPath 'spm_${{ github.ref_name }}_${{ matrix.os_name }}_${{ matrix.version }}.zip'
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: spm*.zip
