# compile matlab when a commit with the keyword "compile" is made
name: Compile MEX
on:
    workflow_dispatch:
    push:

jobs:
    compile_mex:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      mex_ext: mexa64
                    - os: windows-latest
                      mex_ext: mexw64

        steps:
            - name: Set up MATLAB
              uses: matlab-actions/setup-matlab@v2
            - name: Checkout spm/spm/
              uses: actions/checkout@v4
              with:
                  repository: spm/spm
            - name: Compile MEX files
              run: |
                make -C src distclean
                make -C src
                make -C src install
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: spm-matlab-${{ matrix.os }}
                  path: ./**/*.${{ matrix.mex_ext }}


    merge_artifacts:
        runs-on: ubuntu-latest
        needs: compile_mex
        steps:
            - name: Download Linux Artifact
              uses: actions/download-artifact@v4
              with:
                  name: spm-matlab-linux
                  path: artifacts/linux

            - name: Download macOS Artifact
              uses: actions/download-artifact@v4
              with:
                  name: spm-matlab-macos
                  path: artifacts/macos 

            - name: Download Windows Artifact
              uses: actions/download-artifact@v4
              with:
                  name: spm-matlab-windows
                  path: artifacts/windows

            - name: Merge Artifacts
              run: |
                  mkdir -p artifacts/all
                  cp -r artifacts/linux/* artifacts/all/
                  cp -r artifacts/macos/* artifacts/all/
                  cp -r artifacts/windows/* artifacts/all/

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: spm-matlab
                  path: artifacts/all
