# compile matlab when a commit with the keyword "compile" is made
name: Compile MATLAB
on:
    workflow_dispatch:
    push:

jobs:
    compile_matlab:
        runs-on: ubuntu-latest
        steps:
            - name: Set up MATLAB
              uses: matlab-actions/setup-matlab@v2
            - name: Checkout spm/spm/
              uses: actions/checkout@v4
              with:
                  repository: spm/spm
            - name: Compile MEX files
              run: |
                make -C src distclean
                make -C src
                make -C src install
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: spm-matlab
                  path: ./**/*.mexa64
