# compile matlab when a commit with the keyword "compile" is made
name: Compile MEX
on:
    workflow_dispatch:
    push:

jobs:
    compile_mex:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      mex_ext: mexa64
                    - os: macos-latest
                      mex_ext: mexmaci64
                    - os: windows-latest
                      mex_ext: mexw64

        steps:
            - name: Set up MATLAB
              uses: matlab-actions/setup-matlab@v2
            - name: Checkout spm/spm/
              uses: actions/checkout@v4
              with:
                  repository: spm/spm
            - name: Compile MEX files
              run: |
                make -C src distclean
                make -C src
                make -C src install
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: spm-matlab-${{ matrix.os }}
                  path: ./**/*.${{ matrix.mex_ext }}
