name: Test MATLAB Token

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_BATCH_TOKEN }}

jobs:
  verify-token:
    name: Verify MATLAB License Token
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@aa8bbc7b76daa63c5d456d1430cbd6cb5b626ab4 # v2
        with:
          products: MATLAB_Compiler
          release: latest

      - name: Save simple MATLAB file
        run: |
          echo "function y = sumTwoNumbers(x, z)
          y = x + z;
          end" > sumTwoNumbers.m

      - name: Run simple MATLAB compilation
        uses: matlab-actions/run-command@37b454c384483087929a3d652be474ba585a9659 # v2
        with:
          command: |
            mcc -m sumTwoNumbers.m
